# Base configs
baseurl: "https://davidizzle.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Davide Ferretti"
subtitle: "See the world through my eyes!"
author: "Davide Ferretti"
header:
 title: "Photography"
 subtitle: "by Davide Ferretti"
footer:
 name: "Hey there, my name is Davide!"
 bio: "I am an engineer and a tech aficionado from Italy. Photography is what I sometimes do: these are encapsulated pills of the beauty that surrounds us and is within us. Hope you enjoy!"
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/davide.ferretti4"
  instagram: "https://www.instagram.com/davidizzle"
  linkedin: "https://in.linkedin.com/in/davide-ferretti"
  github: "https://www.github.com/davidizzle"
